int bottom = 11;
int middle = 12;
int top = 13;
int northwest = 4;
int north = 3;
int northeast = 2;
int west = 7;
int center = 6;
int east = 5;
int southwest = 10;
int south = 9;
int southeast = 8;
int wait = 100;
const int on = HIGH;
const int off = LOW;

void setup() {                
  
  pinMode(bottom, OUTPUT);
  pinMode(middle, OUTPUT);
  pinMode(top, OUTPUT);
  pinMode(northwest, OUTPUT);
  pinMode(north, OUTPUT);
  pinMode(northeast, OUTPUT);
  pinMode(west, OUTPUT);
  pinMode(center, OUTPUT);
  pinMode(east, OUTPUT);
  pinMode(southwest, OUTPUT);
  pinMode(south, OUTPUT);
  pinMode(southeast, OUTPUT);
}


void loop() {
 
 digitalWrite(northeast, on);
 digitalWrite(north, off);
 digitalWrite(northwest, off);
delay(wait);
 digitalWrite(northeast, off);
 digitalWrite(north, on);
 digitalWrite(northwest, off);
 delay(wait);
  digitalWrite(northeast, off);
 digitalWrite(north, off);
 digitalWrite(northwest, on);
 delay(wait);
digitalWrite(northeast, off);
 digitalWrite(north, off);
 digitalWrite(northwest, off);
 delay(wait);
 digitalWrite(west, on);
 digitalWrite(southwest, off);
 digitalWrite(southeast, off);
 delay(wait);
 digitalWrite(west, off);
 digitalWrite(south, off);
 digitalWrite(southwest, on);
 digitalWrite(southeast, off);
 delay(wait);
  digitalWrite(south, on);
 digitalWrite(southwest, off);
 digitalWrite(southeast, off);
 delay(wait);
  digitalWrite(south, off);
 digitalWrite(southwest, off);
 digitalWrite(southeast, on);
 delay(wait);
   digitalWrite(south, off);
 digitalWrite(southwest, off);
 digitalWrite(southeast, off);
delay(wait);
digitalWrite(east, on);
digitalWrite(center, off);
delay(wait);
digitalWrite(east, off);
digitalWrite(center, on);
delay(wait);
digitalWrite(east, off);
digitalWrite(center, off);
delay(120);
digitalWrite(northeast, on);
 digitalWrite(north, on);
 digitalWrite(northwest, on);
 delay(120);
 digitalWrite(northeast, off);
 digitalWrite(north, off);
 digitalWrite(northwest, off);
 delay(120);
 digitalWrite(west, on);
 digitalWrite(center, on);
 digitalWrite(east, on);
 delay(120);
 digitalWrite(west, off);
 digitalWrite(center, off);
 digitalWrite(east, off);
 delay(120);
    digitalWrite(south, on);
 digitalWrite(southwest, on);
 digitalWrite(southeast, on);
 delay(120);
    digitalWrite(south, off);
 digitalWrite(southwest, off);
 digitalWrite(southeast, off);
delay(90);
 digitalWrite(northwest, on);
 digitalWrite(west, on);
 digitalWrite(southwest, on);
 delay(90);
  digitalWrite(northwest, off);
 digitalWrite(west, off);
 digitalWrite(southwest, off);
 delay(90);
  digitalWrite(north, on);
 digitalWrite(center, on);
 digitalWrite(south, on);
 delay(90);
   digitalWrite(north, off);
 digitalWrite(center, off);
 digitalWrite(south, off);
 delay(90);
   digitalWrite(northeast, on);
 digitalWrite(east, on);
 digitalWrite(southeast, on);
 delay(90);
 digitalWrite(northeast, off);
 digitalWrite(east, off);
 digitalWrite(southeast, off);
 delay(wait);
 
 
}
